### ISSUE TITLE
Add delegate methods for when settings change

### ISSUE THREAD

**Issue by kgn** [kgn/InAppSettings#16]
http://www.iphonedevsdk.com/forum/iphone-sdk-development/41407-app-iphone-preferences.html#post179090

**Comment by kgn** [comment]
Doesn't this just duplicate the functionality of NSUserDefaultsDidChangeNotification?

**Comment by kgn** [comment]
NSUserDefaultsDidChangeNotification doesn't tell you which preference changed.

**Comment by LittleOrangeC** [comment]
A delegate would be nice, but I find some simple logic with NSUserDefaultsDidChangeNotification allows me to get the job done.

**Comment by Tricertops** [comment]
Don't use delegate. Notifications are better, so you would duplicate the `NSUserDefaultsDidChangeNotification` with one difference: you will include `userInfo` dictionary with changed values.

**Comment by kgn** [comment]
There is `InAppSettingsValueChangeNotification`, I'll double check the implementation before closing this issue.

**Comment by kgn** [comment]
I've confirmed that the `InAppSettingsValueChangeNotification` notification is being fired whenever a preference changes in InAppSettings
