### ISSUE TITLE
Color of header title

### ISSUE THREAD

**Issue by pepicrft** [kgn/InAppSettings#20]
Hello, I have used inAppSettings in my App and I have changed the background of the tableview. The problem I have now is that I can't see correctly the titles of groups because the default color is grey. I would like to change it to white. 

¿How can I do that?

Thanks

**Comment by kgn** [comment]
To do it you'll have to use a custom view for the header. In [InAppSettings.m](https://github.com/InScopeApps/InAppSettings/blob/master/InAppSettings/InAppSettings.m) `titleForHeaderInSection` to `viewForHeaderInSection`, look at `viewForFooterInSection` in this file for reference.
